### ISSUE TITLE
Matlab function 'fsolve' can not find the equilibrium point under some initial conditions

### ISSUE THREAD

**Issue by yannsean** [mbarnes1/vehicle-drift#1]
The fsolve function for nonlinear equations is so sensitive to the initial conditions that it often fails to find the answer expected, besides complex dynamics. Is there any empirical method to set the initial value, or a better numerical solver?

**Comment by mbarnes1** [comment]
It looks like back when we wrote this we used a fixed initialization condition. One simple improvement to try would be to do multiple random initializations and pick the best one (especially since the dimensionality is relatively low, this approach should work very well).

**Comment by yannsean** [comment]
Thank a lot! That is indeed a good idea. I think the chanllenge is that if I' d like to find a series of equilibrium points, I have to select each of them mamually. That's quite a job.
